[general]
import = [
  "windows.toml",
  # "kanagawa.toml"
  "gruvbox.toml"
]
live_config_reload = true


[cursor.style]
shape = "Beam"

[font]
size = 18

[font.bold]
family = "Sarasa Term CL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Sarasa Term CL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Sarasa Term CL Nerd Font"
style = "Italic"

[font.normal]
family = "Sarasa Term CL Nerd Font"
style = "Regular"

[scrolling]
history = 100000

[window]
startup_mode = "Maximized"
# opacity = 0.1

[terminal]
