[general]
import = [
  "windows.toml",
  # "kanagawa.toml"
  "gruvbox.toml"
]
live_config_reload = true


[cursor.style]
shape = "Beam"

[scrolling]
history = 100000

[window]
startup_mode = "Maximized"
# opacity = 0.1

[terminal]
