[general]
import = [
  "windows.toml",
  # "kanagawa.toml"
  "gruvbox.toml",
]
live_config_reload = true

[cursor.style]
shape = "Beam"

[scrolling]
history = 100000

[window]
startup_mode = "Maximized"
# opacity = 0.1

[mouse]
bindings = [


  # { mouse = "Back", chars = "H" },
  # { mouse = "Forward", chars = "L"},
]

[keyboard]
bindings = [
  # { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "T", mods = "Control|Shift", action = "CreateNewTab" },
]

[terminal]
