[terminal.shell]
args = ["--nologo"]
program = "pwsh"

[general]
working_directory = '''C:\Users\bennyyip'''

[font]
size = 16

[font.bold]
family = "Iosevka Fixed Curly"
style = "Bold"

[font.bold_italic]
family = "Iosevka Fixed Curly"
style = "Bold Italic"

[font.italic]
family = "Iosevka Fixed Curly"
style = "Italic"

[font.normal]
family = "Iosevka Fixed Curly"
style = "Regular"
