#!/bin/sh
# /usr/bin/i3-scrot
#
# simple screenshot-script using scrot for manjaro-i3 by oberon@manjaro.org
# fork by yebenmy@protonmail.com


if [ "$2" == -t ]
then
  scrot_dir=/tmp/screenshot
else
  scrot_dir=~/pictures/screenshot
fi

if ! [ -d $scrot_dir ]; then
	mkdir -p $scrot_dir
fi

case "$1" in
	--desk|-d|$NULL)
		cd $scrot_dir
    echo -n $scrot_dir/ &&
    scrot -z -e 'echo $f' &&
		sleep 1 &&
		notify-send "screenshot has been saved in $scrot_dir"
		;;
	--window|-w)
		cd $scrot_dir
    echo -n $scrot_dir/ &&
		scrot -z -u -e 'echo $f' &&
		sleep 1 &&
		notify-send "screenshot has been saved in $scrot_dir"
		;;
	--select|-s)
		cd $scrot_dir
		notify-send 'select an area for the screenshot' &
    echo -n $scrot_dir/ &&
		scrot -z -s -e 'echo $f' &&
		sleep 1 && notify-send "screenshot has been saved in $scrot_dir"
		;;
	--help|-h)
		echo "
available options:
-d | --desk    full screen
-w | --window  active window
-s | --select  selection
-h | --help    display this information

Default option is 'full screen'.

The file destination can be set in ${_conf}.
Default is $scrot_dir
"
		;;
	*)
		echo "
== ! i3-scrot: missing or wrong argument ! ==

available options:
-d | --desk    full screen
-w | --window  active window
-s | --select  selection
-h | --help    display this information

Default option is 'full screen'.

The file destination can be set in ${_conf}.
Default is $scrot_dir
"

        exit 2
esac

exit 0
