
[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.dim]
black = "0x333333"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xdddddd"
yellow = "0xffcc66"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[cursor.style]
shape = "Block"

[font]
size = 14

[font.bold]
family = "Sarasa Term CL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Sarasa Term CL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Sarasa Term CL Nerd Font"
style = "Italic"

[font.normal]
family = "Sarasa Term CL Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "None"
key = "Return"
mods = "Alt"

[scrolling]
history = 100000

[terminal.shell]
args = ["--nologo"]
program = "pwsh"

[window]
startup_mode = "Maximized"

[general]
live_config_reload = true

[terminal]
