#!/bin/bash -e
cd "$(dirname "${BASH_SOURCE[0]}")"
./install -c minimal.yaml
grep -qxF 'let g:minimal_plugins = v:true' $HOME/local.vim >/dev/null 2>&1|| echo 'let g:minimal_plugins = v:true' > $HOME/local.vim
which starship >/dev/null 2>&1 || curl -sS https://starship.rs/install.sh | sh
