# General {{{1
POWER          quit
PLAY           set pause no
PAUSE          set pause yes
PLAYPAUSE      cycle pause
STOP           stop
REWIND         seek -30
FORWARD        seek  30
PREV           playlist-prev
NEXT           playlist-next

MBTN_MID       quit-watch-later
MBTN_BACK      playlist-prev
MBTN_FORWARD   playlist-next
MBTN_LEFT      ignore
MBTN_LEFT_DBL  cycle pause
MBTN_RIGHT     script-binding select/context-menu
MBTN_RIGHT_DBL ignore
MBTN_BACK      sub-seek -1
MBTN_FORWARD   sub-seek 1
WHEEL_DOWN     cycle-values speed 3 2 1.75 1.5 1
WHEEL_UP       cycle-values speed 1 1.5 1.75 2 3

tab            script-message-to modernz osc-visibility cycle true

Alt+1          set window-scale 1.0
ESC            set fullscreen no
ENTER          cycle fullscreen
SPACE          cycle pause
HOME           seek 0 absolute
END            seek -1 absolute
UP             osd-msg add volume 5
DOWN           osd-msg add volume -5
LEFT           seek -5
RIGHT          seek  5
Ctrl+UP        playlist-prev
Ctrl+DOWN      playlist-next
PGUP           playlist-prev
PGDWN          playlist-next

Alt+z          cycle secondary-sid
Alt+v          cycle secondary-sub-visibility

q              quit-watch-later
Q              quit

m              cycle mute
M              cycle sub-visibility

-              set play-direction -
=              set play-direction +

# PLAYBACK {{{1
CTRL+v   update-clipboard text; loadfile ${clipboard/text}; show-text '+ ${clipboard/text}'

,        frame-back-step
.        frame-step
L        ab-loop
[        cycle-values speed 3 2 1.75 1.5 1
]        cycle-values speed 1 1.5 1.75 2 3
{        add speed -0.1
}        add speed  0.1
BS       set speed 1
c        add audio-delay -0.1
v        add audio-delay  0.1
z        add sub-delay -0.1
x        add sub-delay +0.1
Shift+BS set audio-delay 0 ; set sub-delay 0

j        no-osd sub-seek  1
k        no-osd sub-seek -1
J        no-osd sub-seek  1; set pause yes
K        no-osd sub-seek -1; set pause yes


1        add chapter -1
2        add chapter 1
9        add chapter -1
0        add chapter 1

S        script-binding toggle-seeker

# VIDEO {{{1
!       add contrast -1
@       add contrast  1
SHARP   add brightness -1
$       add brightness  1
%       add gamma -1
^       add gamma  1
&       add saturation -1
*       add saturation  1
(       add hue -1
)       add hue  1
Ctrl+BS set contrast 0 ; set brightness 0 ; set gamma 0 ; set saturation 0 ; set hue 0

# Shaders {{{1
CTRL+0           change-list glsl-shaders clr ""

# TOOL {{{1
i           script-binding    display-stats-toggle
`           script-binding    console/enable
Ctrl+r      script-message-to save_global_props clean_data
t           cycle             ontop

Ctrl+s      async             screenshot
# SELECT {{{1

l script-binding select/select-playlist
C script-binding select/select-chapter
h script-binding select/select-watch-history

g ignore
g-p script-binding select/select-playlist
g-s script-binding select/select-sid
g-S script-binding select/select-secondary-sid
g-a script-binding select/select-aid
g-v script-binding select/select-vid
g-t script-binding select/select-track
g-c script-binding select/select-chapter
g-e script-binding select/select-edition
g-l script-binding select/select-subtitle-line
g-d script-binding select/select-audio-device
g-h script-binding select/select-watch-history
g-w script-binding select/select-watch-later
g-b script-binding select/select-binding
g-r script-binding select/show-properties
g-m script-binding select/menu

# Modeline {{{1
# vim:fdm=marker
