# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$time\
$username\
$localip\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$ocaml\
$python\
$terraform\
$nix_shell\
$conda\
$memory_usage\
$aws\
$env_var\
$cmd_duration\
$line_break\
$battery\
$character"""

[username]
format = ' [$user]($style)'

[localip]
ssh_only = true
format = '@[$localipv4]($style)'
style = 'bold cyan'
disabled = false

# [hostname]
# ssh_only = true
# format = '[$ssh_symbol](bold blue) [$hostname](bold red) '
# ssh_symbol = 'SSH'
# trim_at = '.companyname.com'
# disabled = false

[directory]
truncation_length = 0
truncate_to_repo = false
use_os_path_sep = false
# fish_style_pwd_dir_length = 2
format = ' [ω $path]($style)[$read_only]($read_only_style) '
style = "fg:142"

[character]
success_symbol = "[λ](bold yellow)"
error_symbol = "[X](bold red)"
vimcmd_symbol = "[❮](purple)"

[time]
style = "fg:74"
disabled = false
format = '[$time]($style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
disabled = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[nodejs]
symbol = 'JS '
format = '[$symbol($version )]($style)'

[python]
symbol = 'PY '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ocaml]
format = '[\(@$switch_name\) ]($style)'
