; Generated by komorebic.exe
Class Komorebic {
    ; static Start(ffm, await_configuration, tcp_port) {
    ;     RunWait("komorebic.exe start " ffm " --await-configuration " await_configuration " --tcp-port " tcp_port, , "Hide")
    ; }

    static Start() {
        RunWait("komorebic.exe start -a", , "Hide")
    }

    static Stop() {
        RunWait("komorebic.exe stop", , "Hide")
    }

    static State() {
        RunWait("komorebic.exe state", , "Hide")
    }

    static Query(state_query) {
        RunWait("komorebic.exe query " state_query, , "Hide")
    }

    static Subscribe(named_pipe) {
        RunWait("komorebic.exe subscribe " named_pipe, , "Hide")
    }

    static Unsubscribe(named_pipe) {
        RunWait("komorebic.exe unsubscribe " named_pipe, , "Hide")
    }

    static Log() {
        RunWait("komorebic.exe log", , "Hide")
    }

    static QuickSaveResize() {
        RunWait("komorebic.exe quick-save-resize", , "Hide")
    }

    static QuickLoadResize() {
        RunWait("komorebic.exe quick-load-resize", , "Hide")
    }

    static SaveResize(path) {
        RunWait("komorebic.exe save-resize " path, , "Hide")
    }

    static LoadResize(path) {
        RunWait("komorebic.exe load-resize " path, , "Hide")
    }

    static Focus(operation_direction) {
        RunWait("komorebic.exe focus " operation_direction, , "Hide")
    }

    static Move(operation_direction) {
        RunWait("komorebic.exe move " operation_direction, , "Hide")
    }

    static Minimize() {
        RunWait("komorebic.exe minimize", , "Hide")
    }

    static Close() {
        RunWait("komorebic.exe close", , "Hide")
    }

    static ForceFocus() {
        RunWait("komorebic.exe force-focus", , "Hide")
    }

    static CycleFocus(cycle_direction) {
        RunWait("komorebic.exe cycle-focus " cycle_direction, , "Hide")
    }

    static CycleMove(cycle_direction) {
        RunWait("komorebic.exe cycle-move " cycle_direction, , "Hide")
    }

    static Stack(operation_direction) {
        RunWait("komorebic.exe stack " operation_direction, , "Hide")
    }

    static Resize(edge, sizing) {
        RunWait("komorebic.exe resize " edge " " sizing, , "Hide")
    }

    static ResizeAxis(axis, sizing) {
        RunWait("komorebic.exe resize-axis " axis " " sizing, , "Hide")
    }

    static Unstack() {
        RunWait("komorebic.exe unstack", , "Hide")
    }

    static CycleStack(cycle_direction) {
        RunWait("komorebic.exe cycle-stack " cycle_direction, , "Hide")
    }

    static MoveToMonitor(target) {
        RunWait("komorebic.exe move-to-monitor " target, , "Hide")
    }

    static CycleMoveToMonitor(cycle_direction) {
        RunWait("komorebic.exe cycle-move-to-monitor " cycle_direction, , "Hide")
    }

    static MoveToWorkspace(target) {
        RunWait("komorebic.exe move-to-workspace " target, , "Hide")
    }

    static MoveToNamedWorkspace(workspace) {
        RunWait("komorebic.exe move-to-named-workspace " workspace, , "Hide")
    }

    static CycleMoveToWorkspace(cycle_direction) {
        RunWait("komorebic.exe cycle-move-to-workspace " cycle_direction, , "Hide")
    }

    static SendToMonitor(target) {
        RunWait("komorebic.exe send-to-monitor " target, , "Hide")
    }

    static CycleSendToMonitor(cycle_direction) {
        RunWait("komorebic.exe cycle-send-to-monitor " cycle_direction, , "Hide")
    }

    static SendToWorkspace(target) {
        RunWait("komorebic.exe send-to-workspace " target, , "Hide")
    }

    static SendToNamedWorkspace(workspace) {
        RunWait("komorebic.exe send-to-named-workspace " workspace, , "Hide")
    }

    static CycleSendToWorkspace(cycle_direction) {
        RunWait("komorebic.exe cycle-send-to-workspace " cycle_direction, , "Hide")
    }

    static SendToMonitorWorkspace(target_monitor, target_workspace) {
        RunWait("komorebic.exe send-to-monitor-workspace " target_monitor " " target_workspace, , "Hide")
    }

    static FocusMonitor(target) {
        RunWait("komorebic.exe focus-monitor " target, , "Hide")
    }

    static FocusWorkspace(target) {
        RunWait("komorebic.exe focus-workspace " target, , "Hide")
    }

    static FocusMonitorWorkspace(target_monitor, target_workspace) {
        RunWait("komorebic.exe focus-monitor-workspace " target_monitor " " target_workspace, , "Hide")
    }

    static FocusNamedWorkspace(workspace) {
        RunWait("komorebic.exe focus-named-workspace " workspace, , "Hide")
    }

    static CycleMonitor(cycle_direction) {
        RunWait("komorebic.exe cycle-monitor " cycle_direction, , "Hide")
    }

    static CycleWorkspace(cycle_direction) {
        RunWait("komorebic.exe cycle-workspace " cycle_direction, , "Hide")
    }

    static MoveWorkspaceToMonitor(target) {
        RunWait("komorebic.exe move-workspace-to-monitor " target, , "Hide")
    }

    static NewWorkspace() {
        RunWait("komorebic.exe new-workspace", , "Hide")
    }

    static ResizeDelta(pixels) {
        RunWait("komorebic.exe resize-delta " pixels, , "Hide")
    }

    static InvisibleBorders(left, top, right, bottom) {
        RunWait("komorebic.exe invisible-borders " left " " top " " right " " bottom, , "Hide")
    }

    static GlobalWorkAreaOffset(left, top, right, bottom) {
        RunWait("komorebic.exe global-work-area-offset " left " " top " " right " " bottom, , "Hide")
    }

    static MonitorWorkAreaOffset(monitor, left, top, right, bottom) {
        RunWait("komorebic.exe monitor-work-area-offset " monitor " " left " " top " " right " " bottom, , "Hide")
    }

    static AdjustContainerPadding(sizing, adjustment) {
        RunWait("komorebic.exe adjust-container-padding " sizing " " adjustment, , "Hide")
    }

    static AdjustWorkspacePadding(sizing, adjustment) {
        RunWait("komorebic.exe adjust-workspace-padding " sizing " " adjustment, , "Hide")
    }

    static ChangeLayout(default_layout) {
        RunWait("komorebic.exe change-layout " default_layout, , "Hide")
    }

    static LoadCustomLayout(path) {
        RunWait("komorebic.exe load-custom-layout " path, , "Hide")
    }

    static FlipLayout(axis) {
        RunWait("komorebic.exe flip-layout " axis, , "Hide")
    }

    static Promote() {
        RunWait("komorebic.exe promote", , "Hide")
    }

    static PromoteFocus() {
        RunWait("komorebic.exe promote-focus", , "Hide")
    }

    static Retile() {
        RunWait("komorebic.exe retile", , "Hide")
    }

    static MonitorIndexPreference(index_preference, left, top, right, bottom) {
        RunWait("komorebic.exe monitor-index-preference " index_preference " " left " " top " " right " " bottom, , "Hide")
    }

    static EnsureWorkspaces(monitor, workspace_count) {
        RunWait("komorebic.exe ensure-workspaces " monitor " " workspace_count, , "Hide")
    }

    static EnsureNamedWorkspaces(monitor, names) {
        RunWait("komorebic.exe ensure-named-workspaces " monitor " " names, , "Hide")
    }

    static ContainerPadding(monitor, workspace, size) {
        RunWait("komorebic.exe container-padding " monitor " " workspace " " size, , "Hide")
    }

    static NamedWorkspaceContainerPadding(workspace, size) {
        RunWait("komorebic.exe named-workspace-container-padding " workspace " " size, , "Hide")
    }

    static WorkspacePadding(monitor, workspace, size) {
        RunWait("komorebic.exe workspace-padding " monitor " " workspace " " size, , "Hide")
    }

    static NamedWorkspacePadding(workspace, size) {
        RunWait("komorebic.exe named-workspace-padding " workspace " " size, , "Hide")
    }

    static WorkspaceLayout(monitor, workspace, value) {
        RunWait("komorebic.exe workspace-layout " monitor " " workspace " " value, , "Hide")
    }

    static NamedWorkspaceLayout(workspace, value) {
        RunWait("komorebic.exe named-workspace-layout " workspace " " value, , "Hide")
    }

    static WorkspaceCustomLayout(monitor, workspace, path) {
        RunWait("komorebic.exe workspace-custom-layout " monitor " " workspace " " path, , "Hide")
    }

    static NamedWorkspaceCustomLayout(workspace, path) {
        RunWait("komorebic.exe named-workspace-custom-layout " workspace " " path, , "Hide")
    }

    static WorkspaceLayoutRule(monitor, workspace, at_container_count, layout) {
        RunWait("komorebic.exe workspace-layout-rule " monitor " " workspace " " at_container_count " " layout, , "Hide")
    }

    static NamedWorkspaceLayoutRule(workspace, at_container_count, layout) {
        RunWait("komorebic.exe named-workspace-layout-rule " workspace " " at_container_count " " layout, , "Hide")
    }

    static WorkspaceCustomLayoutRule(monitor, workspace, at_container_count, path) {
        RunWait("komorebic.exe workspace-custom-layout-rule " monitor " " workspace " " at_container_count " " path, , "Hide")
    }

    static NamedWorkspaceCustomLayoutRule(workspace, at_container_count, path) {
        RunWait("komorebic.exe named-workspace-custom-layout-rule " workspace " " at_container_count " " path, , "Hide")
    }

    static ClearWorkspaceLayoutRules(monitor, workspace) {
        RunWait("komorebic.exe clear-workspace-layout-rules " monitor " " workspace, , "Hide")
    }

    static ClearNamedWorkspaceLayoutRules(workspace) {
        RunWait("komorebic.exe clear-named-workspace-layout-rules " workspace, , "Hide")
    }

    static WorkspaceTiling(monitor, workspace, value) {
        RunWait("komorebic.exe workspace-tiling " monitor " " workspace " " value, , "Hide")
    }

    static NamedWorkspaceTiling(workspace, value) {
        RunWait("komorebic.exe named-workspace-tiling " workspace " " value, , "Hide")
    }

    static WorkspaceName(monitor, workspace, value) {
        RunWait("komorebic.exe workspace-name " monitor " " workspace " " value, , "Hide")
    }

    static ToggleWindowContainerBehaviour() {
        RunWait("komorebic.exe toggle-window-container-behaviour", , "Hide")
    }

    static TogglePause() {
        RunWait("komorebic.exe toggle-pause", , "Hide")
    }

    static ToggleTiling() {
        RunWait("komorebic.exe toggle-tiling", , "Hide")
    }

    static ToggleFloat() {
        RunWait("komorebic.exe toggle-float", , "Hide")
    }

    static ToggleMonocle() {
        RunWait("komorebic.exe toggle-monocle", , "Hide")
    }

    static ToggleMaximize() {
        RunWait("komorebic.exe toggle-maximize", , "Hide")
    }

    static RestoreWindows() {
        RunWait("komorebic.exe restore-windows", , "Hide")
    }

    static Manage() {
        RunWait("komorebic.exe manage", , "Hide")
    }

    static Unmanage() {
        RunWait("komorebic.exe unmanage", , "Hide")
    }

    static ReloadConfiguration() {
        RunWait("komorebic.exe reload-configuration", , "Hide")
    }

    static WatchConfiguration(boolean_state) {
        RunWait("komorebic.exe watch-configuration " boolean_state, , "Hide")
    }

    static CompleteConfiguration() {
        RunWait("komorebic.exe complete-configuration", , "Hide")
    }

    static AltFocusHack(boolean_state) {
        RunWait("komorebic.exe alt-focus-hack " boolean_state, , "Hide")
    }

    static WindowHidingBehaviour(hiding_behaviour) {
        RunWait("komorebic.exe window-hiding-behaviour " hiding_behaviour, , "Hide")
    }

    static CrossMonitorMoveBehaviour(move_behaviour) {
        RunWait("komorebic.exe cross-monitor-move-behaviour " move_behaviour, , "Hide")
    }

    static ToggleCrossMonitorMoveBehaviour() {
        RunWait("komorebic.exe toggle-cross-monitor-move-behaviour", , "Hide")
    }

    static UnmanagedWindowOperationBehaviour(operation_behaviour) {
        RunWait("komorebic.exe unmanaged-window-operation-behaviour " operation_behaviour, , "Hide")
    }

    static FloatRule(identifier, id) {
        RunWait("komorebic.exe float-rule " identifier " `"" id "`"", , "Hide")
    }

    static ManageRule(identifier, id) {
        RunWait("komorebic.exe manage-rule " identifier " `"" id "`"", , "Hide")
    }

    static WorkspaceRule(identifier, id, monitor, workspace) {
        RunWait("komorebic.exe workspace-rule " identifier " `"" id "`" " monitor " " workspace, , "Hide")
    }

    static NamedWorkspaceRule(identifier, id, workspace) {
        RunWait("komorebic.exe named-workspace-rule " identifier " `"" id "`" " workspace, , "Hide")
    }

    static IdentifyObjectNameChangeApplication(identifier, id) {
        RunWait("komorebic.exe identify-object-name-change-application " identifier " `"" id "`"", , "Hide")
    }

    static IdentifyTrayApplication(identifier, id) {
        RunWait("komorebic.exe identify-tray-application " identifier " `"" id "`"", , "Hide")
    }

    static IdentifyLayeredApplication(identifier, id) {
        RunWait("komorebic.exe identify-layered-application " identifier " `"" id "`"", , "Hide")
    }

    static IdentifyBorderOverflowApplication(identifier, id) {
        RunWait("komorebic.exe identify-border-overflow-application " identifier " `"" id "`"", , "Hide")
    }

    static ActiveWindowBorder(boolean_state) {
        RunWait("komorebic.exe active-window-border " boolean_state, , "Hide")
    }

    static ActiveWindowBorderColour(r, g, b, window_kind) {
        RunWait("komorebic.exe active-window-border-colour " r " " g " " b " --window-kind " window_kind, , "Hide")
    }

    static ActiveWindowBorderWidth(width) {
        RunWait("komorebic.exe active-window-border-width " width, , "Hide")
    }

    static ActiveWindowBorderOffset(offset) {
        RunWait("komorebic.exe active-window-border-offset " offset, , "Hide")
    }

    static FocusFollowsMouse(boolean_state, implementation) {
        RunWait("komorebic.exe focus-follows-mouse " boolean_state " --implementation " implementation, , "Hide")
    }

    static ToggleFocusFollowsMouse(implementation) {
        RunWait("komorebic.exe toggle-focus-follows-mouse  --implementation " implementation, , "Hide")
    }

    static MouseFollowsFocus(boolean_state) {
        RunWait("komorebic.exe mouse-follows-focus " boolean_state, , "Hide")
    }

    static ToggleMouseFollowsFocus() {
        RunWait("komorebic.exe toggle-mouse-follows-focus", , "Hide")
    }

    static AhkLibrary() {
        RunWait("komorebic.exe ahk-library", , "Hide")
    }

    static AhkAppSpecificConfiguration(path, override_path) {
        RunWait("komorebic.exe ahk-app-specific-configuration " path " " override_path, , "Hide")
    }

    static PwshAppSpecificConfiguration(path, override_path) {
        RunWait("komorebic.exe pwsh-app-specific-configuration " path " " override_path, , "Hide")
    }

    static FormatAppSpecificConfiguration(path) {
        RunWait("komorebic.exe format-app-specific-configuration " path, , "Hide")
    }

    static NotificationSchema() {
        RunWait("komorebic.exe notification-schema", , "Hide")
    }

    static SocketSchema() {
        RunWait("komorebic.exe socket-schema", , "Hide")
    }

}
