#Include "%A_ScriptDir%\AppSpecific\Anki.ahk"
#Include "%A_ScriptDir%\AppSpecific\DOOMEternal.ahk"
#Include "%A_ScriptDir%\AppSpecific\DOTA2.ahk"
#Include "%A_ScriptDir%\AppSpecific\SumatraPDF.ahk"
#Include "%A_ScriptDir%\AppSpecific\Everything.ahk"
