icons = "awesome"

[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = ""

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 0.5
alert = 0.5

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

# [[block]]
# block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"
