add_newline = false
format =  """$time\
    $custom\
    $kubernetes\
    $directory\
    $git_branch\
    $docker_context\
    $python\
    $package\
    $cmd_duration\
    $status\
    $jobs\
    $line_break\
    $character"""

[custom.username]
command = "whoami"
when = """test "$SSH_CONNECTION" != ''"""
style = "fg:114"
format = "[$symbol$output]($style)"

[custom.ip]
command = """ip -o -4 addr | awk -F "inet |/" '!/127.0.0.1/ {print $2}' | sort -n | head -n 1"""
when = """test "$SSH_CONNECTION" != ''"""
style = "fg:174"
format = "@[$symbol$output]($style) "

[directory]
style = "fg:142"
truncation_length = 999
truncate_to_repo = true
fish_style_pwd_dir_length = 2
format = "ω [$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[λ](bold yellow)"
error_symbol = "[λ](bold red)"
vicmd_symbol = "[λ](bold green)"

[time]
format = '[$time ]($style)'
style = "fg:74"
disabled = false

[status]
style = "bg:red"
format = '[$status]($style) '
map_symbol = true
disabled = false

[python]
symbol = 'PY '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[package]
symbol = 'PKG '
format = "[$symbol$version]($style) "

[git_branch]
format = '[\($branch\)](yellow) '
