add_newline = false
prompt_order =  [
    "time",
    "custom.username",
    "custom.ip",
    "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "docker_context",
    "package",
    "dotnet",
    "elixir",
    "elm",
    "erlang",
    "golang",
    "haskell",
    "java",
    "julia",
    "nodejs",
    "ocaml",
    "php",
    "purescript",
    "python",
    "ruby",
    "rust",
    "terraform",
    "zig",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "crystal",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "character",
]

[custom.username]
command = "whoami"
when = """test "$SSH_CONNECTION" != ''"""
prefix = ""
style = "fg:114"

[custom.ip]
command = """ip -o -4 addr | awk -F "inet |/" '!/127.0.0.1/ {print $2}' | sort -n | head -n 1"""
when = """test "$SSH_CONNECTION" != ''"""
style = "fg:174"
symbol="@ "
prefix = ""

[directory]
prefix = "ω "
style = "fg:142"
truncation_length = 999
truncate_to_repo = true
fish_style_pwd_dir_length = 2

[character]
symbol = "λ"
style_success = "fg:yellow"

[time]
style = "fg:74"
disabled = false

[git_status]
disabled = true

