layout=modern-compact
visibility_modes=auto_always

seekbarkeyframes=yes

osc_on_seek=no
osc_on_start=no

fullscreen_button=no
hide_empty_playlist_button=yes
info_button=no
jump_buttons=no
loop_button=no
ontop_button=no
screenshot_button=no
shuffle_button=no
track_nextprev_buttons=no
window_controls=no

speed_button_scroll=0.5

show_window_title=yes
windowcontrols_independent=no
hover_effect=size,color
hover_effect_color=#00aeec

cache_info=yes
cache_info_speed=yes

fade_blur_strength=30
osc_fade_strength=30
fadein=no

seek_handle_border_hover_size=0
seek_handle_border_size=0
seek_handle_color=#FFFFFF
seek_handle_size=0.3
seekbar_cache_color=#000000
seekbarbg_color=#F2F0E5
seekbarfg_color=#00aeec
nibble_color=#00aeec

slider_rounded_corners=no
thumbnail_box_radius=0
thumbnail_box_padding=0

persistent_progress=yes
persistent_progress_height=10

title=${?pause==yes:⏸}${?mute==yes:🔇}${?ontop==yes:📌}${media-title}


# osc_height=40
# playpause_size=24
# midbuttons_size=20
# sidebuttons_size=20
# title_font_size=22

sub_margins=no
