fadein=no
fullscreen_button=no
hide_empty_playlist_button=yes
hover_effect_color=#00aeec
jump_buttons=no
layout=modern-compact
nibble_color=#00aeec
ontop_button=no
persistent_progress=yes
seek_handle_color=#FFFFFF
seek_handle_size=0.3
seekbarbg_color=#F2F0E5
seekbarfg_color=#00aeec
show_title=no
show_window_title=yes
shuffle_button=yes
slider_rounded_corners=no
sub_margins=no
thumbnail_box_radius=0
title=${?pause==yes:⏸}${?mute==yes:🔇}${?ontop==yes:📌}${media-title}
track_nextprev_buttons=no
visibility_modes=auto_always
window_controls=no
