# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$time\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$ocaml\
$php\
$purescript\
$python\
$ruby\
$rust\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$env_var\
$crystal\
$cmd_duration\
$line_break\
$battery\
$character"""

# [custom.username]
# command = "whoami"
# when = """test "$SSH_CONNECTION" != ''"""
# prefix = ""
# style = "fg:114"

# [custom.ip]
# command = """ip -o -4 addr | awk -F "inet |/" '!/127.0.0.1/ {print $2}' | sort -n | head -n 1"""
# when = """test "$SSH_CONNECTION" != ''"""
# style = "fg:174"
# symbol="@ "
# prefix = ""

[directory]
truncation_length = 999
truncate_to_repo = false
# fish_style_pwd_dir_length = 2
format = '[ω $path]($style)[$read_only]($read_only_style) '
style = "fg:142"

[character]
success_symbol = "[λ](bold yellow)"
error_symbol = "[X](bold red)"
vimcmd_symbol = "[❮](purple)"

[time]
style = "fg:74"
disabled = false
format = '[$time]($style) '

[git_status]
disabled = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[nodejs]
format = '[$symbol]($style)'

[python]
format = '[$symbol]($style)'
